Login.o:Login.c 
	gcc -c Login.c
Register.o:Register.c 
	gcc -c RegisterModule.c
ContactModule.o:ContactModule.c 
	gcc -c ContactModule.c
WriteModule.o:WriteModule.c 
	gcc -c WriteModule.c
RecieveModule.o:RecieveModule.c 
	gcc -c RecieveModule.c
ClientSocket.o:ClientSocket.c
	gcc  -c  ClientSocket.c 
bianyi:Login.o Register.o ContactModule.o WriteModule.o RecieveModule.o ClientSocket.o
clean:
	rm *.o 